### PR TITLE
Changing taco-remote-lib to store the handle to idevicedebugserverpro…

### PR DESCRIPTION
**Pull request by MSLaguana**
…xy in a global variable to be explicitly shared between instances

idevicedebugserverproxy (more specifically the port that we configure it to use) is essentially a shared resource, and this change makes that explicit. If we end up running multiple instances of taco-remote-lib consecutively in order to handle multiple incompatible versions of Cordova, this change makes sure that the packages will check in a known, shared location to access the proxy. An identical change is needed on top of taco-remote-lib@1.2.0 to allow it to cooperate as well.

### CODE REVIEW

**Comment by MSLaguana** [comment]
See https://github.com/Microsoft/TACO/tree/fixConcurrentTacoRemoteLibPackages1.2.0 for the other side of things. Not sure how best to coordinate all this; don't really want that branch to merge into master, but we do want to keep it around so we can do more hotfixes / updates in future.

**Comment by meenakb** [comment]
Looks good to me. Will you be sending another PR for hotfix on taco-remote-lib@1.2.0?

**Comment by MSLaguana** [comment]
I'm not sure how best to do that; It shouldn't be merged into master / v1.2.0 branch, but it also doesn't make sense to be an addition to the v1.1.0 branch (since it has all the other fixes/changes made for the upcoming release as well, it just excludes some small set of things)

**Comment by MSLaguana** [comment]
I am going to close this PR and open up another one against the v1.2.0 branch though.

**Pull request closed without merging**
