### PR TITLE
Update commands in README.md

### PR DESCRIPTION
**Pull request by alebelcor**
Update examples of commands to GFM code block syntax.

### CODE REVIEW

**Comment by nisheetjain** [comment]
Alejandro, thanks for the contribution. 
Can you please send a new PR following the CLA (licensing) process. I have enabled CLA for TACO, you should get a mail when you create a new PR now..

**Comment by alebelcor** [comment]
What does that mean? There's no mention of this (I think) in the `README.md`.

**Comment by nisheetjain** [comment]
It is similar to Legal section [here] (https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md). I was in the impression that an automatic mail gets sent to any external contributor but looks like my understanding is not complete. I will try to get a "How to contribute" section in README. Give me couple of days to get that :)

**Comment by nisheetjain** [comment]
@alebelcor I have added [CONTRIBUTING.md](https://github.com/Microsoft/TACO/blob/master/CONTRIBUTING.md) to TACO. Let me know if you have any questions around CLA signing.

**Pull request merged**
