### PR TITLE
Holding back livereload for the moment.

### PR DESCRIPTION
**Pull request by joshuaskelton**
## Changes
- Commenting out references to livereload in run and emulate commands.
- Removed livereload and devicesync from command help.
- Removed livereload dependency.

### CODE REVIEW

**Comment by nisheetjain** [comment]
:+1:  Assuming gulp clean && gulp run-tests work

**Comment by joshuaskelton** [comment]
I've added an additional commit removing livereload from the tests. I've verified that gulp clean && gulp run-tests runs cleanly.

**Comment by meenakb** [comment]
You may want to remove "import livereload = require("taco-livereload");" from cordovaWrapper.ts in taco-utils. It does not seem to be used.

**Comment by joshuaskelton** [comment]
Good catch Meena.

**Pull request merged**
