### PR TITLE
Fixing a typo in a filename

### PR DESCRIPTION
**Pull request by MSLaguana**

### CODE REVIEW

**Comment by MSLaguana** [comment]
This is the fix for issue #52

**Comment by nisheetjain** [comment]
Taco Kits tests still refer to the file with it's previous name. we need to fix those as well

**Comment by MSLaguana** [comment]
Good point. Maybe we should add a Linux box to our test system as well to catch these issues.

**Comment by nisheetjain** [comment]
:+1:

**Pull request merged**
