### PR TITLE
Removing a platform should remove the corresponding entry from config.xml

### PR DESCRIPTION
**Pull request by meenakb**

### CODE REVIEW

**Comment by nisheetjain** [comment]
:+1:

**Comment by MSLaguana** [comment]
I see a check for whether the user has done "taco platform add platform@version", but that check will also apply to "taco platform rm platform@version". Cordova seems to basically do nothing if you specify such an argument, do we behave appropriately?

**Comment by meenakb** [comment]
"cordova platform remove platform@version" is a no-op. TACO should and does not update the platforms or config.xml in this case.

**Comment by MSLaguana** [comment]
Sounds good. Looks good to me.

**Pull request merged**
