### PR TITLE
Fixing another filename capitalization issue.

### PR DESCRIPTION
**Pull request by MSLaguana**
Pull request #50 already solved issue #66, but while double checking all our require()s I found this one more that was incorrect.

### CODE REVIEW

**Comment by omefire** [comment]
I think we have another issue around 'taco run'. it's around a module named 'remoteBuild' or something.

**Comment by omefire** [comment]
Maybe, it would make sense trying taco-cli on a Unix-based OS, at least the main workflow: create, platform add, plugin add, run, etc...

That might go a long way in helping flush those capitalization issues.

**Comment by MSLaguana** [comment]
I agree

**Comment by MSLaguana** [comment]
Ok, with this commit I've actually gone and tested it out on a Linux box (Ubuntu specifically) and it was able to run tests, so it _should_ be good now.

**Comment by omefire** [comment]
Awesome. Thanks Jimmy!

**Comment by nisheetjain** [comment]
:+1:

**Comment by meenakb** [comment]
:+1:

**Pull request merged**
