### PR TITLE
Removing alias tests for now

### PR DESCRIPTION
**Pull request by joshuaskelton**

### CODE REVIEW

**Comment by MSLaguana** [comment]
Do the original tests pass when you remove the aliasing tests?

**Comment by joshuaskelton** [comment]
Again, the issue is how we test commands. We don't correctly construct them, and the aliasing is broken. I've created a task on myself to fix this.

**Comment by joshuaskelton** [comment]
I've kicked off a test run for the changes. Looks good now.

**Comment by MSLaguana** [comment]
If the issue was a change in the expected output, perhaps we can re-enabled the aliasing tests as well?

**Comment by joshuaskelton** [comment]
I've updated the test expectations and added back the alias tests. Doing a run to verify the issue is fixed.

**Comment by MSLaguana** [comment]
Looks good to me

**Pull request merged**
